### PR TITLE
fix: Fix parser not locating `TranslateService` in private fields using the `#` syntax

### LINKED ISSUE #54: Service parser is not locating the TranslateService if it is a private field
The service parser fails to extract translation keys when the `TranslateService` is assigned to a private field using the JavaScript private field syntax (#). For example, from the code below the key 'hello.world' is not extracted:

```ts
import {Component, inject} from '@angular/core';
import {TranslateService} from '@ngx-translate/core';

@Component({
  selector: 'my-component',
  template: `<p>{{ translatedText }}</p>`
})
export class MyComponent {
  readonly #translate = inject(TranslateService);
  translatedText = '';

  constructor() {
    this.translatedText = this.#translate.instant('hello.world');
  }
}

```

### PR DESCRIPTION
**Pull request by pmpak**
Fixes #54

### CODE REVIEW

File: src/utils/ast-helpers.ts [hunk 1]
```diff
@@ -142,15 +146,15 @@ export function findClassPropertiesConstructorParameterByType(node: ClassDeclara
 }
 
 export function findClassPropertiesDeclarationByType(node: ClassDeclaration, type: string): string[] {
-	const query = `PropertyDeclaration:has(TypeReference > Identifier[name="${type}"]) > Identifier`;
-	const result = tsquery<Identifier>(node, query);
-	return result.map((n) => n.text);
+	const query = `PropertyDeclaration:has(TypeReference > Identifier[name="${type}"])`;
```
Comment (pmpak) [inline src/utils/ast-helpers.ts:149]: To make it capture both `Identifier` and `PrivateIdentifier` I reduced the specificity of the query and then extract the identifier from the AST instead of getting it directly from the query.

File: src/utils/ast-helpers.ts [hunk 2]
```diff
@@ -179,22 +183,23 @@ export function findPropertyCallExpressions(node: Node, prop: string, fnName: st
...
-			tsquery(n.parent, 'PropertyAccessExpression > ThisKeyword').length > 0 &&
-			tsquery(n.parent.parent, `PropertyAccessExpression > Identifier[name=/^(${fnName})$/]`).length > 0
-		) {
-			result.push(n.parent.parent.parent as CallExpression);
+
+	const query = `CallExpression > PropertyAccessExpression:has(Identifier[name=/^(${fnName})$/]):has(PropertyAccessExpression:has(ThisKeyword))`;
+	const result = tsquery<PropertyAccessExpression>(node, query);
+
+	const nodes: CallExpression[] = [];
+	result.forEach((n) => {
```
Comment (pmpak) [inline src/utils/ast-helpers.ts:191]: Similar here, I reduced the specificity of the query and then manually filter out the `CallExpression` nodes from the AST, so that both private and public properties are matched.

**Comment by pmpak** [comment]
@michaelbromley could you take a quick look?
